#cloud-config
package_update: true
package_upgrade: true

packages:
  - git
  - python3
  - python3-pip

runcmd:
  # Klone das GitHub-Repository in das Verzeichnis /opt/flask-login-app
  - git clone https://github.com/Mafezzoli-dev/flask-login-app/master.git /opt/flask-login-app

  # Wechsle in das Projektverzeichnis
  - cd /opt/flask-login-app

  # Installiere alle benötigten Python-Abhängigkeiten (z.B. Flask)
  - pip3 install -r requirements.txt

  # Starte die Flask-Anwendung im Hintergrund auf Port 5000
  - nohup python3 /opt/flask-login-app/app.py > /opt/flask-login-app/flask.log 2>&1 &
